<?php
/**
 * RepricingItemApi
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\Amzn\RePricing\V1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu amzn RePricing API
 *
 * eSagu API to reprice items on amazon.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace eSagu\Amzn\RePricing\V1\eSagu\Amzn\RePricing\V1\Api;

use \eSagu\Amzn\RePricing\V1\ApiClient;
use \eSagu\Amzn\RePricing\V1\ApiException;
use \eSagu\Amzn\RePricing\V1\Configuration;
use \eSagu\Amzn\RePricing\V1\ObjectSerializer;

/**
 * RepricingItemApi Class Doc Comment
 *
 * @category Class
 * @package  eSagu\Amzn\RePricing\V1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RepricingItemApi
{
    /**
     * API Client
     *
     * @var \eSagu\Amzn\RePricing\V1\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \eSagu\Amzn\RePricing\V1\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\eSagu\Amzn\RePricing\V1\ApiClient $apiClient = null)
    {
        if ($apiClient === null) {
            $apiClient = new ApiClient();
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \eSagu\Amzn\RePricing\V1\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \eSagu\Amzn\RePricing\V1\ApiClient $apiClient set the API client
     *
     * @return RepricingItemApi
     */
    public function setApiClient(\eSagu\Amzn\RePricing\V1\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation callList
     *
     * Gets a list of repricing items.
     *
     * @param string $by_sku  (optional)
     * @param bool $by_sku_exact  (optional, default to false)
     * @param string $by_title  (optional)
     * @param bool $by_title_exact  (optional, default to false)
     * @param string $by_asin  (optional)
     * @param string $by_search_term  (optional)
     * @param int $by_amazon_price_from  (optional)
     * @param int $by_amazon_price_to  (optional)
     * @param string $by_price_mode  (optional)
     * @param string $by_price_state  (optional)
     * @param string $by_condition  (optional)
     * @param string $by_fulfillment_type  (optional)
     * @param bool $by_no_price_settings  (optional, default to false)
     * @param string $by_buy_box_strategy  (optional)
     * @param int $by_price_gaps  (optional)
     * @param int $by_exclusion_criteria  (optional)
     * @param int $by_shipping_costs  (optional)
     * @param int $by_buy_box  (optional)
     * @param bool $by_missing_rules  (optional, default to false)
     * @param bool $by_quantity_greater_zero  (optional, default to true)
     * @param bool $by_quantity_equal_zero  (optional, default to false)
     * @param int $by_id_greater_than  (optional)
     * @param bool $has_buy_box  (optional, default to false)
     * @param int $by_custom_code  (optional)
     * @param string $sort  (optional, default to ITEM_ID)
     * @param string $order  (optional, default to ASC)
     * @param int $offset  (optional, default to 0)
     * @param int $limit  (optional, default to 50)
     * @param bool $count_items  (optional, default to false)
     * @param bool $return_items  (optional, default to true)
     * @throws \eSagu\Amzn\RePricing\V1\ApiException on non-2xx response
     * @return \eSagu\Amzn\RePricing\V1\eSagu\Amzn\RePricing\V1\Model\RepricingItemDTO[]
     */
    public function callList($by_sku = null, $by_sku_exact = null, $by_title = null, $by_title_exact = null, $by_asin = null, $by_search_term = null, $by_amazon_price_from = null, $by_amazon_price_to = null, $by_price_mode = null, $by_price_state = null, $by_condition = null, $by_fulfillment_type = null, $by_no_price_settings = null, $by_buy_box_strategy = null, $by_price_gaps = null, $by_exclusion_criteria = null, $by_shipping_costs = null, $by_buy_box = null, $by_missing_rules = null, $by_quantity_greater_zero = null, $by_quantity_equal_zero = null, $by_id_greater_than = null, $has_buy_box = null, $by_custom_code = null, $sort = null, $order = null, $offset = null, $limit = null, $count_items = null, $return_items = null)
    {
        list($response) = $this->callListWithHttpInfo($by_sku, $by_sku_exact, $by_title, $by_title_exact, $by_asin, $by_search_term, $by_amazon_price_from, $by_amazon_price_to, $by_price_mode, $by_price_state, $by_condition, $by_fulfillment_type, $by_no_price_settings, $by_buy_box_strategy, $by_price_gaps, $by_exclusion_criteria, $by_shipping_costs, $by_buy_box, $by_missing_rules, $by_quantity_greater_zero, $by_quantity_equal_zero, $by_id_greater_than, $has_buy_box, $by_custom_code, $sort, $order, $offset, $limit, $count_items, $return_items);
        return $response;
    }

    /**
     * Operation callListWithHttpInfo
     *
     * Gets a list of repricing items.
     *
     * @param string $by_sku  (optional)
     * @param bool $by_sku_exact  (optional, default to false)
     * @param string $by_title  (optional)
     * @param bool $by_title_exact  (optional, default to false)
     * @param string $by_asin  (optional)
     * @param string $by_search_term  (optional)
     * @param int $by_amazon_price_from  (optional)
     * @param int $by_amazon_price_to  (optional)
     * @param string $by_price_mode  (optional)
     * @param string $by_price_state  (optional)
     * @param string $by_condition  (optional)
     * @param string $by_fulfillment_type  (optional)
     * @param bool $by_no_price_settings  (optional, default to false)
     * @param string $by_buy_box_strategy  (optional)
     * @param int $by_price_gaps  (optional)
     * @param int $by_exclusion_criteria  (optional)
     * @param int $by_shipping_costs  (optional)
     * @param int $by_buy_box  (optional)
     * @param bool $by_missing_rules  (optional, default to false)
     * @param bool $by_quantity_greater_zero  (optional, default to true)
     * @param bool $by_quantity_equal_zero  (optional, default to false)
     * @param int $by_id_greater_than  (optional)
     * @param bool $has_buy_box  (optional, default to false)
     * @param int $by_custom_code  (optional)
     * @param string $sort  (optional, default to ITEM_ID)
     * @param string $order  (optional, default to ASC)
     * @param int $offset  (optional, default to 0)
     * @param int $limit  (optional, default to 50)
     * @param bool $count_items  (optional, default to false)
     * @param bool $return_items  (optional, default to true)
     * @throws \eSagu\Amzn\RePricing\V1\ApiException on non-2xx response
     * @return array of \eSagu\Amzn\RePricing\V1\eSagu\Amzn\RePricing\V1\Model\RepricingItemDTO[], HTTP status code, HTTP response headers (array of strings)
     */
    public function callListWithHttpInfo($by_sku = null, $by_sku_exact = null, $by_title = null, $by_title_exact = null, $by_asin = null, $by_search_term = null, $by_amazon_price_from = null, $by_amazon_price_to = null, $by_price_mode = null, $by_price_state = null, $by_condition = null, $by_fulfillment_type = null, $by_no_price_settings = null, $by_buy_box_strategy = null, $by_price_gaps = null, $by_exclusion_criteria = null, $by_shipping_costs = null, $by_buy_box = null, $by_missing_rules = null, $by_quantity_greater_zero = null, $by_quantity_equal_zero = null, $by_id_greater_than = null, $has_buy_box = null, $by_custom_code = null, $sort = null, $order = null, $offset = null, $limit = null, $count_items = null, $return_items = null)
    {
        // parse inputs
        $resourcePath = "/item";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if ($by_sku !== null) {
            $queryParams['by-sku'] = $this->apiClient->getSerializer()->toQueryValue($by_sku);
        }
        // query params
        if ($by_sku_exact !== null) {
            $queryParams['by-sku-exact'] = $this->apiClient->getSerializer()->toQueryValue($by_sku_exact);
        }
        // query params
        if ($by_title !== null) {
            $queryParams['by-title'] = $this->apiClient->getSerializer()->toQueryValue($by_title);
        }
        // query params
        if ($by_title_exact !== null) {
            $queryParams['by-title-exact'] = $this->apiClient->getSerializer()->toQueryValue($by_title_exact);
        }
        // query params
        if ($by_asin !== null) {
            $queryParams['by-asin'] = $this->apiClient->getSerializer()->toQueryValue($by_asin);
        }
        // query params
        if ($by_search_term !== null) {
            $queryParams['by-search-term'] = $this->apiClient->getSerializer()->toQueryValue($by_search_term);
        }
        // query params
        if ($by_amazon_price_from !== null) {
            $queryParams['by-amazon-price-from'] = $this->apiClient->getSerializer()->toQueryValue($by_amazon_price_from);
        }
        // query params
        if ($by_amazon_price_to !== null) {
            $queryParams['by-amazon-price-to'] = $this->apiClient->getSerializer()->toQueryValue($by_amazon_price_to);
        }
        // query params
        if ($by_price_mode !== null) {
            $queryParams['by-price-mode'] = $this->apiClient->getSerializer()->toQueryValue($by_price_mode);
        }
        // query params
        if ($by_price_state !== null) {
            $queryParams['by-price-state'] = $this->apiClient->getSerializer()->toQueryValue($by_price_state);
        }
        // query params
        if ($by_condition !== null) {
            $queryParams['by-condition'] = $this->apiClient->getSerializer()->toQueryValue($by_condition);
        }
        // query params
        if ($by_fulfillment_type !== null) {
            $queryParams['by-fulfillment-type'] = $this->apiClient->getSerializer()->toQueryValue($by_fulfillment_type);
        }
        // query params
        if ($by_no_price_settings !== null) {
            $queryParams['by-no-price-settings'] = $this->apiClient->getSerializer()->toQueryValue($by_no_price_settings);
        }
        // query params
        if ($by_buy_box_strategy !== null) {
            $queryParams['by-buy-box-strategy'] = $this->apiClient->getSerializer()->toQueryValue($by_buy_box_strategy);
        }
        // query params
        if ($by_price_gaps !== null) {
            $queryParams['by-price-gaps'] = $this->apiClient->getSerializer()->toQueryValue($by_price_gaps);
        }
        // query params
        if ($by_exclusion_criteria !== null) {
            $queryParams['by-exclusion-criteria'] = $this->apiClient->getSerializer()->toQueryValue($by_exclusion_criteria);
        }
        // query params
        if ($by_shipping_costs !== null) {
            $queryParams['by-shipping-costs'] = $this->apiClient->getSerializer()->toQueryValue($by_shipping_costs);
        }
        // query params
        if ($by_buy_box !== null) {
            $queryParams['by-buy-box'] = $this->apiClient->getSerializer()->toQueryValue($by_buy_box);
        }
        // query params
        if ($by_missing_rules !== null) {
            $queryParams['by-missing-rules'] = $this->apiClient->getSerializer()->toQueryValue($by_missing_rules);
        }
        // query params
        if ($by_quantity_greater_zero !== null) {
            $queryParams['by-quantity-greater-zero'] = $this->apiClient->getSerializer()->toQueryValue($by_quantity_greater_zero);
        }
        // query params
        if ($by_quantity_equal_zero !== null) {
            $queryParams['by-quantity-equal-zero'] = $this->apiClient->getSerializer()->toQueryValue($by_quantity_equal_zero);
        }
        // query params
        if ($by_id_greater_than !== null) {
            $queryParams['by-id-greater-than'] = $this->apiClient->getSerializer()->toQueryValue($by_id_greater_than);
        }
        // query params
        if ($has_buy_box !== null) {
            $queryParams['has-buy-box'] = $this->apiClient->getSerializer()->toQueryValue($has_buy_box);
        }
        // query params
        if ($by_custom_code !== null) {
            $queryParams['by-custom-code'] = $this->apiClient->getSerializer()->toQueryValue($by_custom_code);
        }
        // query params
        if ($sort !== null) {
            $queryParams['sort'] = $this->apiClient->getSerializer()->toQueryValue($sort);
        }
        // query params
        if ($order !== null) {
            $queryParams['order'] = $this->apiClient->getSerializer()->toQueryValue($order);
        }
        // query params
        if ($offset !== null) {
            $queryParams['offset'] = $this->apiClient->getSerializer()->toQueryValue($offset);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = $this->apiClient->getSerializer()->toQueryValue($limit);
        }
        // query params
        if ($count_items !== null) {
            $queryParams['count-items'] = $this->apiClient->getSerializer()->toQueryValue($count_items);
        }
        // query params
        if ($return_items !== null) {
            $queryParams['return-items'] = $this->apiClient->getSerializer()->toQueryValue($return_items);
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('Authorization');
        if (strlen($apiKey) !== 0) {
            $headerParams['Authorization'] = $apiKey;
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\eSagu\Amzn\RePricing\V1\eSagu\Amzn\RePricing\V1\Model\RepricingItemDTO[]',
                '/item'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\eSagu\Amzn\RePricing\V1\eSagu\Amzn\RePricing\V1\Model\RepricingItemDTO[]', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\eSagu\Amzn\RePricing\V1\eSagu\Amzn\RePricing\V1\Model\RepricingItemDTO[]', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation get
     *
     * Get a single repricing item specified by it's id.
     *
     * @param int $item_id  (required)
     * @throws \eSagu\Amzn\RePricing\V1\ApiException on non-2xx response
     * @return \eSagu\Amzn\RePricing\V1\eSagu\Amzn\RePricing\V1\Model\RepricingItemDTO
     */
    public function get($item_id)
    {
        list($response) = $this->getWithHttpInfo($item_id);
        return $response;
    }

    /**
     * Operation getWithHttpInfo
     *
     * Get a single repricing item specified by it's id.
     *
     * @param int $item_id  (required)
     * @throws \eSagu\Amzn\RePricing\V1\ApiException on non-2xx response
     * @return array of \eSagu\Amzn\RePricing\V1\eSagu\Amzn\RePricing\V1\Model\RepricingItemDTO, HTTP status code, HTTP response headers (array of strings)
     */
    public function getWithHttpInfo($item_id)
    {
        // verify the required parameter 'item_id' is set
        if ($item_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $item_id when calling get');
        }
        // parse inputs
        $resourcePath = "/item/{itemId}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // path params
        if ($item_id !== null) {
            $resourcePath = str_replace(
                "{" . "itemId" . "}",
                $this->apiClient->getSerializer()->toPathValue($item_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('Authorization');
        if (strlen($apiKey) !== 0) {
            $headerParams['Authorization'] = $apiKey;
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\eSagu\Amzn\RePricing\V1\eSagu\Amzn\RePricing\V1\Model\RepricingItemDTO',
                '/item/{itemId}'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\eSagu\Amzn\RePricing\V1\eSagu\Amzn\RePricing\V1\Model\RepricingItemDTO', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\eSagu\Amzn\RePricing\V1\eSagu\Amzn\RePricing\V1\Model\RepricingItemDTO', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
}
