<?php
/**
 * ExclusionCriterionRatingDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\Amzn\RePricing\V1
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu amzn RePricing API
 *
 * eSagu API to reprice items on amazon.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace eSagu\Amzn\RePricing\V1\eSagu\Amzn\RePricing\V1\Model;

use \ArrayAccess;

/**
 * ExclusionCriterionRatingDTO Class Doc Comment
 *
 * @category    Class
 * @package     eSagu\Amzn\RePricing\V1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExclusionCriterionRatingDTO implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'ExclusionCriterionRatingDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'minimum_rating_count' => 'int',
        'minimum_rating_percentage' => 'int'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'minimum_rating_count' => 'minimumRatingCount',
        'minimum_rating_percentage' => 'minimumRatingPercentage'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'minimum_rating_count' => 'setMinimumRatingCount',
        'minimum_rating_percentage' => 'setMinimumRatingPercentage'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'minimum_rating_count' => 'getMinimumRatingCount',
        'minimum_rating_percentage' => 'getMinimumRatingPercentage'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['minimum_rating_count'] = isset($data['minimum_rating_count']) ? $data['minimum_rating_count'] : null;
        $this->container['minimum_rating_percentage'] = isset($data['minimum_rating_percentage']) ? $data['minimum_rating_percentage'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if (!is_null($this->container['minimum_rating_count']) && ($this->container['minimum_rating_count'] > 2147483647)) {
            $invalid_properties[] = "invalid value for 'minimum_rating_count', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['minimum_rating_count']) && ($this->container['minimum_rating_count'] < 0)) {
            $invalid_properties[] = "invalid value for 'minimum_rating_count', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['minimum_rating_percentage']) && ($this->container['minimum_rating_percentage'] > 100)) {
            $invalid_properties[] = "invalid value for 'minimum_rating_percentage', must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['minimum_rating_percentage']) && ($this->container['minimum_rating_percentage'] < 0)) {
            $invalid_properties[] = "invalid value for 'minimum_rating_percentage', must be bigger than or equal to 0.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['minimum_rating_count'] > 2147483647) {
            return false;
        }
        if ($this->container['minimum_rating_count'] < 0) {
            return false;
        }
        if ($this->container['minimum_rating_percentage'] > 100) {
            return false;
        }
        if ($this->container['minimum_rating_percentage'] < 0) {
            return false;
        }
        return true;
    }


    /**
     * Gets minimum_rating_count
     * @return int
     */
    public function getMinimumRatingCount()
    {
        return $this->container['minimum_rating_count'];
    }

    /**
     * Sets minimum_rating_count
     * @param int $minimum_rating_count
     * @return $this
     */
    public function setMinimumRatingCount($minimum_rating_count)
    {

        if (!is_null($minimum_rating_count) && ($minimum_rating_count > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $minimum_rating_count when calling ExclusionCriterionRatingDTO., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($minimum_rating_count) && ($minimum_rating_count < 0)) {
            throw new \InvalidArgumentException('invalid value for $minimum_rating_count when calling ExclusionCriterionRatingDTO., must be bigger than or equal to 0.');
        }

        $this->container['minimum_rating_count'] = $minimum_rating_count;

        return $this;
    }

    /**
     * Gets minimum_rating_percentage
     * @return int
     */
    public function getMinimumRatingPercentage()
    {
        return $this->container['minimum_rating_percentage'];
    }

    /**
     * Sets minimum_rating_percentage
     * @param int $minimum_rating_percentage
     * @return $this
     */
    public function setMinimumRatingPercentage($minimum_rating_percentage)
    {

        if (!is_null($minimum_rating_percentage) && ($minimum_rating_percentage > 100)) {
            throw new \InvalidArgumentException('invalid value for $minimum_rating_percentage when calling ExclusionCriterionRatingDTO., must be smaller than or equal to 100.');
        }
        if (!is_null($minimum_rating_percentage) && ($minimum_rating_percentage < 0)) {
            throw new \InvalidArgumentException('invalid value for $minimum_rating_percentage when calling ExclusionCriterionRatingDTO., must be bigger than or equal to 0.');
        }

        $this->container['minimum_rating_percentage'] = $minimum_rating_percentage;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\eSagu\Amzn\RePricing\V1\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\eSagu\Amzn\RePricing\V1\ObjectSerializer::sanitizeForSerialization($this));
    }
}


