<?php
/**
 * PriceGapShippingTimeDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\Amzn\RePricing\V1
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu amzn RePricing API
 *
 * eSagu API to reprice items on amazon.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace eSagu\Amzn\RePricing\V1\Model;

use \ArrayAccess;

/**
 * PriceGapShippingTimeDTO Class Doc Comment
 *
 * @category    Class
 * @description A single price gap shipping time rule.
 * @package     eSagu\Amzn\RePricing\V1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PriceGapShippingTimeDTO implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'PriceGapShippingTimeDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'max_hours' => 'int',
        'min_hours' => 'int'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'max_hours' => 'maxHours',
        'min_hours' => 'minHours'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'max_hours' => 'setMaxHours',
        'min_hours' => 'setMinHours'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'max_hours' => 'getMaxHours',
        'min_hours' => 'getMinHours'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['max_hours'] = isset($data['max_hours']) ? $data['max_hours'] : null;
        $this->container['min_hours'] = isset($data['min_hours']) ? $data['min_hours'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if (!is_null($this->container['max_hours']) && ($this->container['max_hours'] > 2160)) {
            $invalid_properties[] = "invalid value for 'max_hours', must be smaller than or equal to 2160.";
        }

        if (!is_null($this->container['max_hours']) && ($this->container['max_hours'] < 0)) {
            $invalid_properties[] = "invalid value for 'max_hours', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['min_hours']) && ($this->container['min_hours'] > 2160)) {
            $invalid_properties[] = "invalid value for 'min_hours', must be smaller than or equal to 2160.";
        }

        if (!is_null($this->container['min_hours']) && ($this->container['min_hours'] < 0)) {
            $invalid_properties[] = "invalid value for 'min_hours', must be bigger than or equal to 0.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['max_hours'] > 2160) {
            return false;
        }
        if ($this->container['max_hours'] < 0) {
            return false;
        }
        if ($this->container['min_hours'] > 2160) {
            return false;
        }
        if ($this->container['min_hours'] < 0) {
            return false;
        }
        return true;
    }


    /**
     * Gets max_hours
     * @return int
     */
    public function getMaxHours()
    {
        return $this->container['max_hours'];
    }

    /**
     * Sets max_hours
     * @param int $max_hours
     * @return $this
     */
    public function setMaxHours($max_hours)
    {

        if (!is_null($max_hours) && ($max_hours > 2160)) {
            throw new \InvalidArgumentException('invalid value for $max_hours when calling PriceGapShippingTimeDTO., must be smaller than or equal to 2160.');
        }
        if (!is_null($max_hours) && ($max_hours < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_hours when calling PriceGapShippingTimeDTO., must be bigger than or equal to 0.');
        }

        $this->container['max_hours'] = $max_hours;

        return $this;
    }

    /**
     * Gets min_hours
     * @return int
     */
    public function getMinHours()
    {
        return $this->container['min_hours'];
    }

    /**
     * Sets min_hours
     * @param int $min_hours
     * @return $this
     */
    public function setMinHours($min_hours)
    {

        if (!is_null($min_hours) && ($min_hours > 2160)) {
            throw new \InvalidArgumentException('invalid value for $min_hours when calling PriceGapShippingTimeDTO., must be smaller than or equal to 2160.');
        }
        if (!is_null($min_hours) && ($min_hours < 0)) {
            throw new \InvalidArgumentException('invalid value for $min_hours when calling PriceGapShippingTimeDTO., must be bigger than or equal to 0.');
        }

        $this->container['min_hours'] = $min_hours;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\eSagu\Amzn\RePricing\V1\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\eSagu\Amzn\RePricing\V1\ObjectSerializer::sanitizeForSerialization($this));
    }
}


