<?php
/**
 * RepricingCustomCodeDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\Amzn\RePricing\V1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu amzn RePricing API
 *
 * eSagu API to reprice items on amazon.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace eSagu\Amzn\RePricing\V1;

/**
 * RepricingCustomCodeDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description A custom code. A custom code is a small JavaScript snipped used for individual price calculation. If verified is true the code can be used for optimization. The name must be unique.
/**
 * @package     eSagu\Amzn\RePricing\V1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RepricingCustomCodeDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RepricingCustomCodeDTO"
     */
    public function testRepricingCustomCodeDTO()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "inserted"
     */
    public function testPropertyInserted()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "trigger_price_change"
     */
    public function testPropertyTriggerPriceChange()
    {

    }

    /**
     * Test attribute "updated"
     */
    public function testPropertyUpdated()
    {

    }

    /**
     * Test attribute "use_exclusion_criteria"
     */
    public function testPropertyUseExclusionCriteria()
    {

    }

    /**
     * Test attribute "use_price_gaps"
     */
    public function testPropertyUsePriceGaps()
    {

    }

    /**
     * Test attribute "use_shipping_costs"
     */
    public function testPropertyUseShippingCosts()
    {

    }

    /**
     * Test attribute "verified"
     */
    public function testPropertyVerified()
    {

    }

}
