<?php
/**
 * RepricingItemStrategyDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\Amzn\RePricing\V1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu amzn RePricing API
 *
 * eSagu API to reprice items on amazon.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace eSagu\Amzn\RePricing\V1;

/**
 * RepricingItemStrategyDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description The repricing item&#39;s strategy. The repricing item&#39;s strategy is a container for the item&#39;s strategy and price settings.
/**
 * @package     eSagu\Amzn\RePricing\V1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RepricingItemStrategyDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RepricingItemStrategyDTO"
     */
    public function testRepricingItemStrategyDTO()
    {

    }

    /**
     * Test attribute "buy_box_settings_id"
     */
    public function testPropertyBuyBoxSettingsId()
    {

    }

    /**
     * Test attribute "custom_code_id"
     */
    public function testPropertyCustomCodeId()
    {

    }

    /**
     * Test attribute "exclusion_criteria_id"
     */
    public function testPropertyExclusionCriteriaId()
    {

    }

    /**
     * Test attribute "price_gap_id"
     */
    public function testPropertyPriceGapId()
    {

    }

    /**
     * Test attribute "price_settings"
     */
    public function testPropertyPriceSettings()
    {

    }

    /**
     * Test attribute "shipping_costs_id"
     */
    public function testPropertyShippingCostsId()
    {

    }

}
