<?php
/**
 * RepricingFeedSubmissionDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\Amzn\RePricing\V1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu amzn RePricing API
 *
 * eSagu API to reprice items on amazon.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace eSagu\Amzn\RePricing\V1;

/**
 * RepricingFeedSubmissionDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description RepricingFeedSubmissionDTO
/**
 * @package     eSagu\Amzn\RePricing\V1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RepricingFeedSubmissionDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RepricingFeedSubmissionDTO"
     */
    public function testRepricingFeedSubmissionDTO()
    {

    }

    /**
     * Test attribute "feed_submission_id"
     */
    public function testPropertyFeedSubmissionId()
    {

    }

    /**
     * Test attribute "feed_type"
     */
    public function testPropertyFeedType()
    {

    }

    /**
     * Test attribute "inserted"
     */
    public function testPropertyInserted()
    {

    }

    /**
     * Test attribute "processing_status"
     */
    public function testPropertyProcessingStatus()
    {

    }

    /**
     * Test attribute "updated"
     */
    public function testPropertyUpdated()
    {

    }

}
