<?php
/**
 * RepricingItemDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\Amzn\RePricing\V1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu amzn RePricing API
 *
 * eSagu API to reprice items on amazon.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace eSagu\Amzn\RePricing\V1;

/**
 * RepricingItemDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description A repricing item. A repricing item contains information imported from amzn, information about competing offers infos about the optimized price, the strategy settings and the price upload for example.
/**
 * @package     eSagu\Amzn\RePricing\V1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RepricingItemDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RepricingItemDTO"
     */
    public function testRepricingItemDTO()
    {

    }

    /**
     * Test attribute "amazon_open_date"
     */
    public function testPropertyAmazonOpenDate()
    {

    }

    /**
     * Test attribute "amazon_price"
     */
    public function testPropertyAmazonPrice()
    {

    }

    /**
     * Test attribute "asin"
     */
    public function testPropertyAsin()
    {

    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {

    }

    /**
     * Test attribute "fba"
     */
    public function testPropertyFba()
    {

    }

    /**
     * Test attribute "feed_submission"
     */
    public function testPropertyFeedSubmission()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "initial_price"
     */
    public function testPropertyInitialPrice()
    {

    }

    /**
     * Test attribute "inserted"
     */
    public function testPropertyInserted()
    {

    }

    /**
     * Test attribute "listed"
     */
    public function testPropertyListed()
    {

    }

    /**
     * Test attribute "offers"
     */
    public function testPropertyOffers()
    {

    }

    /**
     * Test attribute "offers_updated"
     */
    public function testPropertyOffersUpdated()
    {

    }

    /**
     * Test attribute "optimization_result"
     */
    public function testPropertyOptimizationResult()
    {

    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {

    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {

    }

    /**
     * Test attribute "strategy"
     */
    public function testPropertyStrategy()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "updated"
     */
    public function testPropertyUpdated()
    {

    }

}
