<?php
/**
 * RepricingSettingsDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\Amzn\RePricing\V1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu amzn RePricing API
 *
 * eSagu API to reprice items on amazon.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace eSagu\Amzn\RePricing\V1;

/**
 * RepricingSettingsDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description The global settings. The global settings contains flags for dis or enabling up and downloads or the number of Amazon MWS API request performed by esagu.
/**
 * @package     eSagu\Amzn\RePricing\V1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RepricingSettingsDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RepricingSettingsDTO"
     */
    public function testRepricingSettingsDTO()
    {

    }

    /**
     * Test attribute "amazon_report_request_max_age"
     */
    public function testPropertyAmazonReportRequestMaxAge()
    {

    }

    /**
     * Test attribute "buy_box_fallback_to_optimization"
     */
    public function testPropertyBuyBoxFallbackToOptimization()
    {

    }

    /**
     * Test attribute "can_not_optimize_rule"
     */
    public function testPropertyCanNotOptimizeRule()
    {

    }

    /**
     * Test attribute "download_enabled"
     */
    public function testPropertyDownloadEnabled()
    {

    }

    /**
     * Test attribute "fba_quantity_update_enabled"
     */
    public function testPropertyFbaQuantityUpdateEnabled()
    {

    }

    /**
     * Test attribute "fba_quantity_update_max_age"
     */
    public function testPropertyFbaQuantityUpdateMaxAge()
    {

    }

    /**
     * Test attribute "maximum_concurrent_uploads"
     */
    public function testPropertyMaximumConcurrentUploads()
    {

    }

    /**
     * Test attribute "maximum_items_per_upload"
     */
    public function testPropertyMaximumItemsPerUpload()
    {

    }

    /**
     * Test attribute "maximum_uploads_per_hour"
     */
    public function testPropertyMaximumUploadsPerHour()
    {

    }

    /**
     * Test attribute "show_expert_settings"
     */
    public function testPropertyShowExpertSettings()
    {

    }

    /**
     * Test attribute "stock_update_max_age"
     */
    public function testPropertyStockUpdateMaxAge()
    {

    }

    /**
     * Test attribute "time_zone"
     */
    public function testPropertyTimeZone()
    {

    }

    /**
     * Test attribute "upload_enabled"
     */
    public function testPropertyUploadEnabled()
    {

    }

}
