<?php
/**
 * RepricingExclusionCriteriaDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\Amzn\RePricing\V1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu amzn RePricing API
 *
 * eSagu API to reprice items on amazon.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace eSagu\Amzn\RePricing\V1;

/**
 * RepricingExclusionCriteriaDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description An exclusion criteria. An exclusion criteria is a set of exclusion criterion. Each exclusion criterion defines if an offer must be excluded form repricing. onlyFeaturedMerchant for example excludes offers by sellers which are not a featured merchant. The name must be unique.
/**
 * @package     eSagu\Amzn\RePricing\V1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RepricingExclusionCriteriaDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RepricingExclusionCriteriaDTO"
     */
    public function testRepricingExclusionCriteriaDTO()
    {

    }

    /**
     * Test attribute "criterion_rating"
     */
    public function testPropertyCriterionRating()
    {

    }

    /**
     * Test attribute "criterion_seller_id"
     */
    public function testPropertyCriterionSellerId()
    {

    }

    /**
     * Test attribute "criterion_shipping_time"
     */
    public function testPropertyCriterionShippingTime()
    {

    }

    /**
     * Test attribute "criterion_ships_from"
     */
    public function testPropertyCriterionShipsFrom()
    {

    }

    /**
     * Test attribute "is_default_fba"
     */
    public function testPropertyIsDefaultFba()
    {

    }

    /**
     * Test attribute "is_default_mfn"
     */
    public function testPropertyIsDefaultMfn()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "only_featured_merchant"
     */
    public function testPropertyOnlyFeaturedMerchant()
    {

    }

    /**
     * Test attribute "own_seller_id"
     */
    public function testPropertyOwnSellerId()
    {

    }

    /**
     * Test attribute "seller_fulfillment_type"
     */
    public function testPropertySellerFulfillmentType()
    {

    }

}
