<?php
/**
 * RepricingPriceGapsDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\Amzn\RePricing\V1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu amzn RePricing API
 *
 * eSagu API to reprice items on amazon.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace eSagu\Amzn\RePricing\V1;

/**
 * RepricingPriceGapsDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description The price gaps. The price gaps defines ow the price should be aligned to a competitors price.A PriceGapDTO without sellerId and fulfillmentType is mandatory as default price gap to use. Further PriceGapDTOs with restriction on the sellerId and/or fulfillmentType are optional. The name must be unique.
/**
 * @package     eSagu\Amzn\RePricing\V1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RepricingPriceGapsDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RepricingPriceGapsDTO"
     */
    public function testRepricingPriceGapsDTO()
    {

    }

    /**
     * Test attribute "is_default_fba"
     */
    public function testPropertyIsDefaultFba()
    {

    }

    /**
     * Test attribute "is_default_mfn"
     */
    public function testPropertyIsDefaultMfn()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "price_gaps"
     */
    public function testPropertyPriceGaps()
    {

    }

    /**
     * Test attribute "shipping_included"
     */
    public function testPropertyShippingIncluded()
    {

    }

}
