<?php
/**
 * RepricingBuyBoxSlotsDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\Amzn\RePricing\V1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu amzn RePricing API
 *
 * eSagu API to reprice items on amazon.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace eSagu\Amzn\RePricing\V1;

/**
 * RepricingBuyBoxSlotsDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description The easyBox slots. Each slot package has got a number of slots and a start date, the end date is optional. If the end date is set, slots can be used until this date.
/**
 * @package     eSagu\Amzn\RePricing\V1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RepricingBuyBoxSlotsDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RepricingBuyBoxSlotsDTO"
     */
    public function testRepricingBuyBoxSlotsDTO()
    {

    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "inserted"
     */
    public function testPropertyInserted()
    {

    }

    /**
     * Test attribute "slot_count"
     */
    public function testPropertySlotCount()
    {

    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {

    }

    /**
     * Test attribute "updated"
     */
    public function testPropertyUpdated()
    {

    }

}
