<?php
/**
 * RepricingBuyBoxSettingsDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\Amzn\RePricing\V1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu amzn RePricing API
 *
 * eSagu API to reprice items on amazon.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace eSagu\Amzn\RePricing\V1;

/**
 * RepricingBuyBoxSettingsDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description The easyBox settings. priceDownPercent is the percentage value of price reduction, 25 stands for 0.25%, for example.priceUpPercent is mandatory for MARGIN strategy and raises the price if the buy box has been catched. The potentialUpTimeout defines the time seconds the price will be aligned with the next higher offer.
/**
 * @package     eSagu\Amzn\RePricing\V1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RepricingBuyBoxSettingsDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RepricingBuyBoxSettingsDTO"
     */
    public function testRepricingBuyBoxSettingsDTO()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "potential_up_timeout"
     */
    public function testPropertyPotentialUpTimeout()
    {

    }

    /**
     * Test attribute "price_down_percent"
     */
    public function testPropertyPriceDownPercent()
    {

    }

    /**
     * Test attribute "price_up_percent"
     */
    public function testPropertyPriceUpPercent()
    {

    }

    /**
     * Test attribute "strategy"
     */
    public function testPropertyStrategy()
    {

    }

}
