<?php
/**
 * RepricingCSVRequestPresetApiTest
 * PHP version 5
 *
 * @category Class
 * @package  eSagu\Amzn\RePricing\V1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eSagu amzn RePricing API
 *
 * eSagu API to reprice items on amazon.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace eSagu\Amzn\RePricing\V1;

use \eSagu\Amzn\RePricing\V1\Configuration;
use \eSagu\Amzn\RePricing\V1\ApiClient;
use \eSagu\Amzn\RePricing\V1\ApiException;
use \eSagu\Amzn\RePricing\V1\ObjectSerializer;

/**
 * RepricingCSVRequestPresetApiTest Class Doc Comment
 *
 * @category Class
 * @package  eSagu\Amzn\RePricing\V1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RepricingCSVRequestPresetApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for callList
     *
     * Gets csv request presets ..
     *
     */
    public function testCallList()
    {

    }

    /**
     * Test case for delete
     *
     * Delete a csv request preset by id..
     *
     */
    public function testDelete()
    {

    }

    /**
     * Test case for get
     *
     * Get a csv request preset specified by it's id..
     *
     */
    public function testGet()
    {

    }

    /**
     * Test case for post
     *
     * Adds a csv request preset..
     *
     */
    public function testPost()
    {

    }

    /**
     * Test case for put
     *
     * Edit a csv request preset..
     *
     */
    public function testPut()
    {

    }

}
